name        : libxshmfence
version     : 1.2
release     : 3
source      :
    - http://xorg.freedesktop.org/releases/individual/lib/libxshmfence-1.2.tar.gz : 58467a0e36fc4ec749dc55f81a4ab3b822c82b6dfb7d36bdb6b28c9fd2a5ccaf
license     : MIT
summary     : X Linux futex event API
builddeps   :
    - pkgconfig(xproto)
    - glibc-32bit-devel
    - libgcc-32bit
emul32      : yes
description : |
    A library that exposes an event API on top of Linux futexes
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
    %make clean
