name       : libxshmfence
version    : '1.3'
release    : 10
source     :
    - https://www.x.org/releases/individual/lib/libxshmfence-1.3.tar.gz : 7eb3d46ad91bab444f121d475b11b39273142d090f7e9ac43e6a87f4ff5f902c
license    : MIT
summary    : X Linux futex event API
component  : xorg.library
description: |
    A library that exposes an event API on top of Linux futexes
builddeps  :
    - pkgconfig(xproto)
emul32     : yes
optimize   : speed
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
