name       : libxshmfence
version    : 1.3.1
release    : 14
source     :
    - https://www.x.org/releases/individual/lib/libxshmfence-1.3.1.tar.gz : 033fdcb4f5efa95b6ca3979e5ba190948e73c50cd9b0ea0a6a45e934c93c3969
license    : MIT
summary    : X Linux futex event API
component  : xorg.library
description: |
    A library that exposes an event API on top of Linux futexes
emul32     : yes
optimize   : speed
builddeps  :
    - pkgconfig(xproto)
setup      : |
    %configure --prefix=/usr \
               --disable-static
build      : |
    %make
install    : |
    %make_install
